<a href="https://colab.research.google.com/github/Kuyjeng/PythonLab5/blob/main/Lab5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

รหัสนักศึกษา : 67015181 ชื่อ :พีรพัฒน์ เครือแก้ว ณ ลำพูน

Exercise 5.1 ให้เขียน function ชื่อ day_of_year(day, month ,year) โดยมีการคืนค่า คือ day_of_years เป็นวันที่ลำดับที่เท่าใดของปีคริสตศักราช year
ปีที่เป็น Leap Year เดือนกุมภาพันธ์จะมี 29 วัน
ให้สร้างฟังก์ชัน is_leap เพื่อตรวจสอบ leap year แยกออกมา และให้ฟังก์ชัน day_of_year เรียกใช้ is_leap อีกที


In [1]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
    if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
        return True
    return False

def day_of_year(day, month, year):
    total_days = sum(days_in_month[:month-1]) + day
    if leap_year(year) and month > 2:
        total_days += 1
    return total_days


# Testcases
print("Normal year (2023):")
print(f"1 Jan 2023: {day_of_year(1, 1, 2023)}")  # ควรได้ 1
print(f"1 Feb 2023: {day_of_year(1, 2, 2023)}")  # ควรได้ 32
print(f"1 Mar 2023: {day_of_year(1, 3, 2023)}")  # ควรได้ 60
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

print("\nLeap year (2024):")
print(f"1 Jan 2024: {day_of_year(1, 1, 2024)}")  # ควรได้ 1
print(f"29 Feb 2024: {day_of_year(29, 2, 2024)}")  # ควรได้ 60
print(f"1 Mar 2024: {day_of_year(1, 3, 2024)}")  # ควรได้ 61
print(f"31 Dec 2024: {day_of_year(31, 12, 2024)}")  # ควรได้ 366

print("\nCentury year, not a leap year (1900):")
print(f"1 Mar 1900: {day_of_year(1, 3, 1900)}")  # ควรได้ 60

print("\nCentury year, leap year (2000):")
print(f"1 Mar 2000: {day_of_year(1, 3, 2000)}")  # ควรได้ 61

print("\nMid-year dates:")
print(f"15 Jun 2023: {day_of_year(15, 6, 2023)}")  # ควรได้ 166
print(f"15 Jun 2024: {day_of_year(15, 6, 2024)}")  # ควรได้ 167 (Leap year)

print("\nLast day of each quarter:")
print(f"31 Mar 2023: {day_of_year(31, 3, 2023)}")  # ควรได้ 90
print(f"30 Jun 2023: {day_of_year(30, 6, 2023)}")  # ควรได้ 181
print(f"30 Sep 2023: {day_of_year(30, 9, 2023)}")  # ควรได้ 273
print(f"31 Dec 2023: {day_of_year(31, 12, 2023)}")  # ควรได้ 365

Normal year (2023):
1 Jan 2023: 1
1 Feb 2023: 32
1 Mar 2023: 60
31 Dec 2023: 365

Leap year (2024):
1 Jan 2024: 1
29 Feb 2024: 60
1 Mar 2024: 61
31 Dec 2024: 366

Century year, not a leap year (1900):
1 Mar 1900: 60

Century year, leap year (2000):
1 Mar 2000: 61

Mid-year dates:
15 Jun 2023: 166
15 Jun 2024: 167

Last day of each quarter:
31 Mar 2023: 90
30 Jun 2023: 181
30 Sep 2023: 273
31 Dec 2023: 365


Exercise 5.2 ให้เขียนฟังก์ชัน เพิ่มเติมเป็น date_diff
รับข้อมูลในรูปแบบ “dd-mm-yyyy” เช่น date_diff(“1-1-2018”, “1-1-2020”) จะได้ 731 วัน date_diff(“25-12-1999”, “9-3-2000”) จะได้ 76 วัน
ให้เขียนฟังก์ชัน day_in_year โดยจะส่งค่าจำนวนวันของปี (365 หรือ 366) โดยรับข้อมูลเป็น ปี
ส่งคืนข้อมูลเป็นจำนวนวันตั้งแต่วันที่แรก จนถึงวันที่สอง โดยรวมทั้ง 2 วันนั้นเข้าไปด้วย
ให้สมมติว่าวันแรก จะต้องมาก่อนวันที่สองเสมอ ดังนั้นไม่ต้องตรวจสอบ


In [6]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

def day_of_year(day, month, year):
    total_days = sum(days_in_month[:month-1]) + day
    if leap_year(year) and month > 2:
        total_days += 1
    return total_days

def days_in_year(year):
    return 366 if leap_year(year) else 365

def date_diff(date1, date2):
    day1, month1, year1 = map(int, date1.split('-'))
    day2, month2, year2 = map(int, date2.split('-'))

    if year1 == year2:
        return day_of_year(day2, month2, year2) - day_of_year(day1, month1, year1)

    days_end_year1 = days_in_year(year1) - day_of_year(day1, month1, year1)
    days_start_year2 = day_of_year(day2, month2, year2)
    total_days = days_end_year1 + days_start_year2

    for year in range(year1 + 1, year2):
        total_days += days_in_year(year)

    return total_days
# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)


730
75
366
365
365
364


Exercise 5.3 จากโปรแกรม 5.2 ให้เขียนฟังก์ชัน date_diff  เพิ่มเติม โดยให้มีการตรวจสอบ
วันที่ต้องเป็นวันที่ถูกต้องของเดือนนั้นๆ
เดือนต้องอยู่ระหว่าง 1-12
เดือนกุมภาพันธ์ของปีที่มี Leap Year เท่านั้นที่จะมี 29 วันได้
หากข้อมูล Input ผิดพลาด ให้ Return -1


In [8]:
days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

def leap_year(year):
    return (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

def valid_date(day, month, year):
    if month < 1 or month > 12:
        return False
    if month == 2 and leap_year(year):
        return 1 <= day <= 29
    return 1 <= day <= days_in_month[month - 1]

def day_of_year(day, month, year):
    total_days = sum(days_in_month[:month-1]) + day
    if leap_year(year) and month > 2:
        total_days += 1
    return total_days

def days_in_year(year):
    return 366 if leap_year(year) else 365

def parse_date(date_str):
    try:
        day, month, year = map(int, date_str.split('-'))
        return day, month, year
    except ValueError:
        return None

def date_diff(date1, date2):
    parsed_date1 = parse_date(date1)
    parsed_date2 = parse_date(date2)

    if not parsed_date1 or not parsed_date2:
        return -1

    day1, month1, year1 = parsed_date1
    day2, month2, year2 = parsed_date2

    if not (valid_date(day1, month1, year1) and valid_date(day2, month2, year2)):
        return -1

    if year1 == year2:
        return day_of_year(day2, month2, year2) - day_of_year(day1, month1, year1)

    days_end_year1 = days_in_year(year1) - day_of_year(day1, month1, year1)
    days_start_year2 = day_of_year(day2, month2, year2)
    total_days = days_end_year1 + days_start_year2

    for year in range(year1 + 1, year2):
        total_days += days_in_year(year)

    return total_days

# ทดสอบฟังก์ชัน
print(date_diff("1-1-2018", "1-1-2020"))  # ควรได้ 731
print(date_diff("25-12-1999", "9-3-2000"))  # ควรได้ 76
print(date_diff("1-1-2000", "1-1-2001"))  # ควรได้ 367 (ปี 2000 เป็น leap year)
print(date_diff("1-1-2001", "1-1-2002"))  # ควรได้ 366 (ปี 2001 ไม่ใช่ leap year)
print(date_diff("1-3-2000", "1-3-2001"))  # ควรได้ 367 (ข้ามปี leap year)
print(date_diff("1-1-2023", "31-12-2023"))  # ควรได้ 365 (ทั้งปี 2023)

# ทดสอบกรณีข้อมูลไม่ถูกต้อง
print(date_diff("31-4-2023", "1-5-2023"))  # ควรได้ -1 (เดือนเมษายนมี 30 วัน)
print(date_diff("29-2-2023", "1-3-2023"))  # ควรได้ -1 (ปี 2023 ไม่ใช่ leap year)
print(date_diff("1-13-2023", "1-1-2024"))  # ควรได้ -1 (เดือนไม่ถูกต้อง)
print(date_diff("abc", "1-1-2024"))  # ควรได้ -1 (รูปแบบวันที่ไม่ถูกต้อง)

730
75
366
365
365
364
-1
-1
-1
-1


1.	ปลาหมอคางดำเพศเมีย 1 ตัว เมื่ออายุครบ 2 เดือน จะสามารถสืบพันธ์ได้ โดยระยะเวลาตั้งท้องจนถึง
วางไข่ของตัวเมียจะใช้เวลา 21 วัน และฟักในปากเพศผู้อีก 7 วัน (สามารถรวมเป็น 1 เดือนได้) โดยออกไข่ครั้งละ 300 ฟอง กำหนดให้ไข่ฟักเป็นเพศผู้และเพศเมียอย่างละครึ่ง และเมื่อวางไข่แล้วจะสามารถสืบพันธ์ต่อได้ทันที กำหนดให้ปลามีอายุ 5 ปี และปลาทั้งหมดจะตาย p% ทุก 1 เดือน จงหาว่าปลาหมอคางดำหลุดจากฟาร์ม n ตัวเป็นเพศผู้และเพศเมียอย่างละครึ่ง จงเขียนโปรแกรมรับค่า n และ p ให้แสดงผลจำนวนปลาทุก 3 เดือน เป็นเวลา 10 ปี ให้เขียนเป็นฟังก์ชัน ชื่อ simulate_fish_population()


In [3]:
import math

def simulate_fish_population(n, p):
    males = n // 2
    females = n // 2
    death_rate = p / 100
    month = 0

    male_age = [0] * males
    female_age = [0] * females

    while month <= 120:
        if month % 3 == 0:
            total_fish = len(male_age) + len(female_age)
            print(f"Month {month}: {total_fish} fish ({len(male_age)} males, {len(female_age)} females)")

        month += 1

        # อีัตราการตาย
        def apply_death_rate(age_list):
            survivors = math.floor(len(age_list) * (1 - death_rate))
            return age_list[:survivors]

        male_age = apply_death_rate(male_age)
        female_age = apply_death_rate(female_age)

        # อายุุเพิ่มขึ้น
        male_age = [age + 1 for age in male_age]
        female_age = [age + 1 for age in female_age]

        # เกิดใหม่่ทุกๆ 3 เดือนสำหรับตัวเมียอายุ 2 เดือน
        new_males = 0
        new_females = 0
        for female in female_age:
            if female >= 2 and (month - female) % 3 == 0:
                new_males += 150
                new_females += 150

        male_age += [0] * new_males
        female_age += [0] * new_females

# Run simulation
simulate_fish_population(2, 10)


# Run simulation
n = 2  # Initial number of fish
p = 10  # Monthly mortality rate

# simulate_fish_population(n, p)

# ถ้าเริ่มต้นด้วยปลา 2 ตัว ตายเดือนละ 10%
# เดือนที่ 1 ไข่ 300 ไบ
# เดือนที่ 2 ไข่ 300 ใบ + ลูกปลา 270 ตัว
# เดือนที่ 3 ไข่ 300 ใบ + ลูกปลา 270 ตัว + ปลาโตเต็มวัย 243 ตัว + 2 = 515 ตัว


Month 0: 2 fish (1 males, 1 females)
Month 3: 0 fish (0 males, 0 females)
Month 6: 0 fish (0 males, 0 females)
Month 9: 0 fish (0 males, 0 females)
Month 12: 0 fish (0 males, 0 females)
Month 15: 0 fish (0 males, 0 females)
Month 18: 0 fish (0 males, 0 females)
Month 21: 0 fish (0 males, 0 females)
Month 24: 0 fish (0 males, 0 females)
Month 27: 0 fish (0 males, 0 females)
Month 30: 0 fish (0 males, 0 females)
Month 33: 0 fish (0 males, 0 females)
Month 36: 0 fish (0 males, 0 females)
Month 39: 0 fish (0 males, 0 females)
Month 42: 0 fish (0 males, 0 females)
Month 45: 0 fish (0 males, 0 females)
Month 48: 0 fish (0 males, 0 females)
Month 51: 0 fish (0 males, 0 females)
Month 54: 0 fish (0 males, 0 females)
Month 57: 0 fish (0 males, 0 females)
Month 60: 0 fish (0 males, 0 females)
Month 63: 0 fish (0 males, 0 females)
Month 66: 0 fish (0 males, 0 females)
Month 69: 0 fish (0 males, 0 females)
Month 72: 0 fish (0 males, 0 females)
Month 75: 0 fish (0 males, 0 females)
Month 78: 0 fish

2.	ให้เขียน function find_mismatch ซึ่งรับ string มา 2 ค่า โดยจะส่งค่ากลับดังนี้
- 0 เมื่อ string ทั้ง 2 ตัว เหมือนกัน โดยไม่สนใจ case
- 1 เมื่อ string 1 จะเหมือน string 2 โดยการลบและ/หรือเพิ่มตัวอักษรเพียง 1 ตัว
- 2 เมื่อ string ไม่เข้าเกณฑ์ 0 หรือ 1


| String  1| 	String2	|ผลลัพธ์|
|----------|----------|------|
|Python|	Java	|2|
|book	 |  boot	|1|
|fan	 |  fun	  |1|
|sin	 | sink	  |1 เพราะเพิ่ม k ใน str2 แล้วจะเหมือนกัน
|Dog	 | dog	  |0
|poke	 | spoke	|1 เพิ่ม s ใน str2 แล้วเหมือนกัน
|poker |	poke	|1 ตัด r ใน str1 ออกแล้วเหมือนกัน






In [5]:
import math

def find_mismatch(s1, s2):
    def are_equal_ignore_case(a, b):
        return a.lower() == b.lower()

    def can_be_equal_by_one_edit(a, b):
        len_a, len_b = len(a), len(b)
        if abs(len_a - len_b) > 1:
            return False

        if len_a > len_b:
            a, b = b, a

        i, j = 0, 0
        edited = False
        while i < len(a) and j < len(b):
            if a[i] != b[j]:
                if edited:
                    return False
                edited = True
                if len_a == len_b:
                    i += 1
            else:
                i += 1
            j += 1
        return True

    if are_equal_ignore_case(s1, s2):
        return 0
    elif can_be_equal_by_one_edit(s1, s2):
        return 1
    else:
        return 2

print(f"{'String 1':<10} {'String 2':<10} {'Result':<10}")
for s1, s2 in test_cases:
    result = find_mismatch(s1, s2)
    print(f"{s1:<10} {s2:<10} {result:<10}")


String 1   String 2   Result    
Python     Java       2         
book       boot       1         
fan        fun        1         
sin        sink       1         
Dog        dog        0         
poke       spoke      1         
poker      poke       1         


3.	จากข้อ 1 ให้เขียนฟังก์ชันชื่อ spelling_correction โดยรับ 2 argument ตัวแรกเป็นประโยค (string) และตัวที่ 2 เป็น list ของคำ (correct_spells) โดยฟังก์ชันนี้มีหน้าที่ตรวจสอบแต่ละ word ใน input string กับคำที่อยู่ใน correct_spells โดยค่าที่คืนกลับมาจะมีดังนี้ (พยายามเรียกใช้ฟังก์ชันในข้อ 1)
-	ถ้าคำที่อยู่ในประโยค ตรงกับคำที่อยู่ใน correct_spells ทุกอย่าง ก็จะ copy ไปที่ output string
-	ถ้าคำที่อยู่ในประโยค ต่างจากคำที่อยู่ใน correct_spells โดยต่างกัน 1 ตัวอักษร โดยการเปลี่ยน การเพิ่ม หรือการลบ 1 ตัวอักษร คำที่อยู่ในประโยคจะถูกเปลี่ยนโดยคำที่อยู่ใน correct_spells และนำไปใส่ output string
-	ถ้าคำที่ไม่พบในเงื่อนไขข้างต้นให้นำคำนั้นไปใส่ output string ได้เลย
-	คำที่ประกอบด้วย 1 หรือ 2 ตัวอักษรจะไม่ตรวจสอบ ให้นำคำนั้นไปใส่ output string ได้เลย
-	ถ้ามี 2 คำใน correct_spells ที่ตรงตามเงื่อนไข ให้ใช้คำแรก
-	ไม่สนใจตัวใหญ่ ตัวเล็ก
-	Input string จะมีได้เพียงอักษรภาษาอังกฤษเท่านั้น
-	ในแต่ละคำจะคั่นด้วย 1 space ถ้ามี space มากกว่านั้นให้ตัดออก และตัด space จากหัวท้ายประโยค

|ประโยค	|correct_spells	|output string |
|-------|---------------|-------------|
|Thes is the Firs cas	|[‘that’,’first’,’case’,’car’]|	thes is the first car|
|programming is fan and easy	|[‘programming’,’this’,’fun’,’easy’,book’]	|programming is fun and easy|
|Thes is vary essy	|[‘this’,’is’,’very’,’easy’]	|this is very easy|
|Wee ipve Pythen	|[‘we’,’live’,’ln’,’Python’]	|we live python|




In [13]:
import math

def find_mismatch(s1, s2):
    for i in range(min(len(s1), len(s2))):
        if s1[i] != s2[i]:
            return i
    return -1

def are_equal_ignore_case(a, b):
    return a.lower() == b.lower()

def can_be_equal_by_one_edit(a, b):
    if abs(len(a) - len(b)) > 1:
        return False

    if len(a) > len(b):
        a, b = b, a

    i, j = 0, 0
    edited = False
    while i < len(a) and j < len(b):
        if a[i] != b[j]:
            if edited:
                return False
            edited = True
            if len(a) == len(b):
                i += 1
        else:
            i += 1
        j += 1
    return True

def correct_word(word, correct_spells):
    word_lower = word.lower()
    for correct in correct_spells:
        if are_equal_ignore_case(word, correct):
            return correct
        if can_be_equal_by_one_edit(word_lower, correct.lower()):
            return correct
    return word

def spelling_correction(sentence, correct_spells):
    words = [word.strip() for word in sentence.split()]
    corrected_words = [correct_word(word, correct_spells) for word in words]
    return ' '.join(corrected_words)

test = [
    ("Thes is the Firs cas", ['that', 'first', 'case', 'car']),
    ("programming is fan and easy", ['programming', 'this', 'fun', 'easy', 'book']),
    ("Thes is vary essy", ['this', 'is', 'very', 'easy']),
    ("Wee ipve Pythen", ['we', 'live', 'ln', 'Python'])
]

print(f"{'ประโยค':<30} {'correct_spells':<30} {'output string':<30}")
for sentence, correct_spells in test:
    result = spelling_correction(sentence, correct_spells)
    print(f"{sentence:<30} {str(correct_spells):<30} {result:<30}")


ประโยค                         correct_spells                 output string                 
Thes is the Firs cas           ['that', 'first', 'case', 'car'] Thes is the first case        
programming is fan and easy    ['programming', 'this', 'fun', 'easy', 'book'] programming is fun and easy   
Thes is vary essy              ['this', 'is', 'very', 'easy'] this is very easy             
Wee ipve Pythen                ['we', 'live', 'ln', 'Python'] we ipve Python                


4. ให้เขียนฟังก์ชัน find_word_horizontal ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามแถวของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t',' e','t','k']]
	word='cat'
	find_word_horizontal(crosswords,word)
```

Output
   [2,1]


In [14]:
def find_word_horizontal(crosswords, word):
    rows = len(crosswords)
    cols = len(crosswords[0]) if rows > 0 else 0
    word_len = len(word)

    for r in range(rows):
        for c in range(cols - word_len + 1):
            if ''.join(crosswords[r][c:c + word_len]) == word:
                return (r, c)

    return None
crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'
print(find_word_horizontal(crosswords, word))


(2, 1)


5. ให้เขียนฟังก์ชัน find_word_vertical ซึ่งจะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตามคอลัมน์ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบ จะส่งคืน row index และ column index ของตัวอักษรแรก ถ้าไม่พบจะส่งคืน None

ตัวอย่าง
```
	crosswords=[['s','d','o','g'],
              ['c','u','c','m'],
              ['a','c','a','t'],
              ['t',' e','t','k']]
	word='cat'
	find_word_vertical(crosswords,word)
```

Output
   [1,0]


In [15]:
def find_word_vertical(crosswords, word):
    rows = len(crosswords)
    cols = len(crosswords[0]) if rows > 0 else 0
    word_len = len(word)

    for c in range(cols):
        for r in range(rows - word_len + 1):
            if ''.join(crosswords[r + i][c] for i in range(word_len)) == word:
                return (r, c)

    return None
crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'
print(find_word_vertical(crosswords, word))


(1, 0)


6.	ให้เขียนฟังก์ชัน capitalize_word_in_crossword จะรับ list ขนาด 2 มิติ ของตัวอักษร (คล้ายกับเกม cross word) และ word ซึ่งเป็น string เป็น argument โดยฟังก์ชันนี้ จะค้นหาตาม row และ column ของ list เพื่อหาตำแหน่งที่มีอักษรตรงกับคำใน word ถ้าพบจะเปลี่ยนเป็นตัวใหญ่และ และส่งคืน list ที่แก้ไขแล้ว แต่ถ้าไม่เจอจะส่ง list เดิมกลับมา ให้ใช้ฟังก์ชันตามข้อ 3 และ 4 ช่วย

```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','x','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
```
จะส่งค่ากลับ
```
 [['s','d','o','g'],
  ['C','u','c','m'],
  ['A','x','a','t'],
  ['T','e','t','k']]
```
```
crosswords=[['s','d','o','g'],
            ['c','u','c','m'],
            ['a','c','a','t'],
            ['t','e','t','k']]
word='cat'
capitalize_word_in_crossword(crosswords,word)
จะส่งค่ากลับ                   
[['s','d','o','g'],
 ['c','u','c','m'],
 ['a','C','A','T'],
 ['t','e','t','k']]
```




In [16]:
def find_word_horizontal(crosswords, word):
    rows = len(crosswords)
    cols = len(crosswords[0]) if rows > 0 else 0
    word_len = len(word)

    for r in range(rows):
        for c in range(cols - word_len + 1):
            if ''.join(crosswords[r][c:c + word_len]) == word:
                return (r, c)

    return None

def find_word_vertical(crosswords, word):
    rows = len(crosswords)
    cols = len(crosswords[0]) if rows > 0 else 0
    word_len = len(word)

    for c in range(cols):
        for r in range(rows - word_len + 1):
            if ''.join(crosswords[r + i][c] for i in range(word_len)) == word:
                return (r, c)

    return None

def capitalize_word_in_crossword(crosswords, word):
    horizontal_pos = find_word_horizontal(crosswords, word)
    if horizontal_pos:
        row, col = horizontal_pos
        for i in range(len(word)):
            crosswords[row][col + i] = crosswords[row][col + i].upper()
        return crosswords

    vertical_pos = find_word_vertical(crosswords, word)
    if vertical_pos:
        row, col = vertical_pos
        for i in range(len(word)):
            crosswords[row + i][col] = crosswords[row + i][col].upper()
        return crosswords

    return crosswords

crosswords = [
    ['s', 'd', 'o', 'g'],
    ['c', 'u', 'c', 'm'],
    ['a', 'c', 'a', 't'],
    ['t', 'e', 't', 'k']
]
word = 'cat'
print(capitalize_word_in_crossword(crosswords, word))


[['s', 'd', 'o', 'g'], ['c', 'u', 'c', 'm'], ['a', 'C', 'A', 'T'], ['t', 'e', 't', 'k']]
